from unittest.mock import patch

import pytest
from sqlalchemy import select

from src.models.parameters import Parameter
from src.models.species import Species
from src.services.ahp_service import AhpService


@pytest.fixture
def ahp_service():
    return AhpService()


@pytest.mark.asyncio
@patch("src.services.ahp_service.get_recommend_config")
async def test_ahp_service_upsert(mock_get_config, ahp_service, async_session):
    """
    Verifies that the AHP service correctly calculates weights and
    upserts (updates/inserts) parameters in the database.
    """
    # Mock YAML config
    mock_get_config.return_value = {"features": {"rainfall_mm": {"type": "numeric", "default_weight": 0.20}, "temperature_celsius": {"type": "numeric", "default_weight": 0.20}}}

    # Setup Test Data (Valid Species based on constraints)
    test_species = Species(
        name="Test Oak",
        common_name="Oak",
        rainfall_mm_min=1000,
        rainfall_mm_max=2000,
        temperature_celsius_min=20,
        temperature_celsius_max=25,
        elevation_m_min=100,
        elevation_m_max=500,
        ph_min=5.5,
        ph_max=7.5,
        coastal=False,
        riparian=False,
        nitrogen_fixing=False,
        shade_tolerant=False,
        bank_stabilising=False,
    )
    async_session.add(test_species)
    await async_session.flush()  # Get the species.id generated by the DB

    # Create an existing parameter to test the UPDATE branch
    existing_param = Parameter(species_id=test_species.id, feature="rainfall_mm", weight=0.10)
    async_session.add(existing_param)
    await async_session.commit()

    # Execute Service
    matrix = [[1.0, 3.0], [0.333, 1.0]]
    result = await ahp_service.calculate_and_save_ahp_weights(async_session, matrix, test_species.id)

    # Verify calculation logic
    assert result["is_consistent"] is True
    assert result["message"] == "Success"

    # Verify database changes
    stmt = select(Parameter).where(Parameter.species_id == test_species.id)
    db_result = await async_session.execute(stmt)
    saved_parameters = db_result.scalars().all()

    param_dict = {p.feature: p for p in saved_parameters}

    assert len(saved_parameters) == 2
    assert round(param_dict["rainfall_mm"].weight, 2) == 0.75
    assert round(param_dict["temperature_celsius"].weight, 2) == 0.25
