"""add species_exclusion_rules table

Revision ID: 54e8117daa73
Revises: 2d5aae317afd
Create Date: 2026-04-02 13:54:06.899770

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54e8117daa73'
down_revision: Union[str, Sequence[str], None] = '2d5aae317afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_exclusion_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_exclusion_rules')
    # ### end Alembic commands ###
