"""add baseline tree count to farms

Revision ID: 56260d49e7ae
Revises: 65bddf16ae44
Create Date: 2026-08-10 12:24:48.816659

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56260d49e7ae'
down_revision: Union[str, Sequence[str], None] = '65bddf16ae44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('baseline_tree_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'baseline_tree_count')
    # ### end Alembic commands ###
