"""Renamed columns based on discussion with Darrin

Revision ID: 3e2b96d54f32
Revises: f9c6de568368
Create Date: 2025-12-07 19:40:17.527458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e2b96d54f32"
down_revision: Union[str, Sequence[str], None] = "f9c6de568368"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("farms", sa.Column("ph", sa.Float(), nullable=False))
    op.drop_column("farms", "soil_ph")
    op.add_column("species", sa.Column("rainfall_mm_min", sa.Integer(), nullable=False))
    op.add_column("species", sa.Column("rainfall_mm_max", sa.Integer(), nullable=False))
    op.add_column(
        "species", sa.Column("temperature_celsius_min", sa.Integer(), nullable=False)
    )
    op.add_column(
        "species", sa.Column("temperature_celsius_max", sa.Integer(), nullable=False)
    )
    op.add_column("species", sa.Column("elevation_m_min", sa.Integer(), nullable=False))
    op.add_column("species", sa.Column("elevation_m_max", sa.Integer(), nullable=False))
    op.add_column("species", sa.Column("ph_min", sa.Float(), nullable=False))
    op.add_column("species", sa.Column("ph_max", sa.Float(), nullable=False))
    op.drop_column("species", "min_elevation_m")
    op.drop_column("species", "min_rainfall_mm")
    op.drop_column("species", "max_elevation_m")
    op.drop_column("species", "min_temp_c")
    op.drop_column("species", "max_temp_c")
    op.drop_column("species", "max_rainfall_mm")
    op.drop_column("species", "min_ph")
    op.drop_column("species", "max_ph")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "species",
        sa.Column(
            "max_ph",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "species",
        sa.Column(
            "min_ph",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "species",
        sa.Column("max_rainfall_mm", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "species",
        sa.Column("max_temp_c", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "species",
        sa.Column("min_temp_c", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "species",
        sa.Column("max_elevation_m", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "species",
        sa.Column("min_rainfall_mm", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "species",
        sa.Column("min_elevation_m", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("species", "ph_max")
    op.drop_column("species", "ph_min")
    op.drop_column("species", "elevation_m_max")
    op.drop_column("species", "elevation_m_min")
    op.drop_column("species", "temperature_celsius_max")
    op.drop_column("species", "temperature_celsius_min")
    op.drop_column("species", "rainfall_mm_max")
    op.drop_column("species", "rainfall_mm_min")
    op.add_column(
        "farms",
        sa.Column(
            "soil_ph",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("farms", "ph")
    # ### end Alembic commands ###
