import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
    container: { maxWidth: '1000px', margin: '0 auto', padding: '60px 20px', fontFamily: 'system-ui, sans-serif' },
    header: { textAlign: 'center', marginBottom: '60px' },
    title: { fontSize: '2.8rem', fontWeight: '800', marginBottom: '40px', letterSpacing: '-0.02em' },
    navWrapper: { display: 'flex', justifyContent: 'center' },
    buttonGroup: { display: 'flex', justifyContent: 'center', gap: '30px', flexWrap: 'wrap', maxWidth: '800px', padding: '10px' },
    actionBtn: { padding: '14px 28px', fontWeight: '600', color: '#007bff', background: '#fff', border: '2px solid #007bff', borderRadius: '10px', cursor: 'pointer', transition: 'all 0.2s ease-in-out', minWidth: '220px' },
    actionBtnActive: { padding: '14px 28px', fontWeight: '600', color: '#fff', background: '#007bff', border: '2px solid #007bff', borderRadius: '10px', cursor: 'pointer', minWidth: '220px', boxShadow: '0 4px 12px rgba(0, 123, 255, 0.25)' },
    viewContainer: { animation: 'fadeIn 0.4s ease-out' },
    viewTitle: { fontSize: '1.75rem', marginBottom: '30px', borderBottom: '2px solid #eee', paddingBottom: '12px' },
    controls: { background: '#f8f9fa', padding: '40px', borderRadius: '16px', display: 'flex', alignItems: 'flex-end', justifyContent: 'center', gap: '24px', border: '1px solid #e9ecef' },
    inputGroup: { display: 'flex', flexDirection: 'column', gap: '10px' },
    label: { fontSize: '0.95rem', fontWeight: 'bold', color: '#444' },
    input: { padding: '14px', borderRadius: '8px', border: '1px solid #ced4da', width: '160px', fontSize: '1rem' },
    primaryBtn: { padding: '14px 28px', backgroundColor: '#28a745', color: '#fff', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold', fontSize: '1rem' },
    disabledBtn: { padding: '14px 28px', backgroundColor: '#adb5bd', color: '#fff', border: 'none', borderRadius: '8px', cursor: 'not-allowed', fontSize: '1rem' },
    resultsCard: { marginTop: '50px', padding: '35px', border: '1px solid #dee2e6', backgroundColor: '#fff', borderRadius: '20px', boxShadow: '0 6px 12px rgba(0,0,0,0.04)' },
    table: { width: '100%', borderCollapse: 'collapse', marginTop: '25px' },
    th: { padding: '16px', textAlign: 'left', borderBottom: '2px solid #eee', color: '#555', fontSize: '0.95rem' },
    td: { padding: '16px', borderBottom: '1px solid #f8f9fa' },
    primaryName: { fontWeight: 'bold', fontSize: '1.1rem', color: '#1a1a1a', marginBottom: '2px' },
    secondaryName: { fontStyle: 'italic', fontSize: '0.9rem', color: '#666' },
    scoreContainer: { display: 'flex', alignItems: 'center', gap: '12px' },
    scoreValue: { minWidth: '50px', fontWeight: 'bold' },
    progressBarBg: { flex: 1, height: '10px', background: '#eee', borderRadius: '5px', overflow: 'hidden' },
    progressBarFill: { height: '100%', transition: 'width 0.6s cubic-bezier(0.4, 0, 0.2, 1)' },
    detailsBtn: { background: 'none', border: '1px solid #007bff', color: '#007bff', borderRadius: '6px', padding: '6px 12px', cursor: 'pointer', fontWeight: '500' },
    expandedRow: { background: '#fafafa' },
    reasonContainer: { padding: '25px', textAlign: 'center' },
    reasonHeader: { marginBottom: '15px', fontWeight: '700', fontSize: '0.9rem', color: '#888', letterSpacing: '0.1em' },
    reasonWrapper: { display: 'flex', justifyContent: 'center' },
    reasonList: { width: '100%', maxWidth: '450px' },
    reasonRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' },
    reasonItem: { borderBottom: '1px solid #eee', padding: '8px 0' },
    errorText: { color: '#d32f2f', textAlign: 'center', marginTop: '25px', padding: '12px', background: '#fee', borderRadius: '8px' },
    welcome: { textAlign: 'center', padding: '100px 40px', border: '2px dashed #e0e0e0', borderRadius: '24px', color: '#999' },
    loadingFull: { display: 'flex', height: '100vh', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem', color: '#007bff' },
    dataGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '20px', marginTop: '25px' },
    dataItem: { padding: '15px', background: '#fcfcfc', border: '1px solid #f0f0f0', borderRadius: '10px', boxShadow: '0 2px 4px rgba(0,0,0,0.02)' },
    placeholderBox: { height: '350px', backgroundColor: '#fafafa', border: '2px dashed #dee2e6', borderRadius: '20px', display: 'flex', alignItems: 'center', justifyContent: 'center', textAlign: 'center' },
    wipContainer: { maxWidth: '450px', padding: '20px' },
    wipTitle: { fontSize: '1.8rem', color: '#856404', marginBottom: '15px' },
    wipText: { color: '#777', lineHeight: '1.6', fontSize: '1.05rem' }
};